Error in <TCling::RegisterModule>: cannot find dictionary module FrameworkDict_rdict.pcm

 *** Break *** floating point exception



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2b1c46d4c700 (LWP 1264157)):
#0  0x0000003051ce91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b1c467753e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1c46771c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002b1c46770447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2b1c46f4d700 (LWP 1264158)):
#0  0x000000305200f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002b1c46770bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1c468b7f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002b1c468b8079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2b1c4714e700 (LWP 1264159)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2b1c4734f700 (LWP 1264160)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2b1c47550700 (LWP 1264161)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b1c39b86d80 (LWP 1264077)):
#0  0x0000003051cac86d in waitpid () from /lib64/libc.so.6
#1  0x0000003051c3e479 in do_system () from /lib64/libc.so.6
#2  0x0000003051c3e7b0 in system () from /lib64/libc.so.6
#3  0x00002b1c3ac1fc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002b1c3ac21bfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002b1c44fd5ef2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002b1c44fd63f5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002b1c46009cb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002b1c6002909f in __cf_44 ()
#10 0x00002b1c3a2762b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002b1c3a276e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002b1c3a25fe7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002b1c3a26d0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002b1c3a26bdf5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002b1c3a26add3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b1c3a267d1b in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002b1c39a7540e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002b1c39a7719b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002b1c39a772be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002b1c39a787c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002b1c39a9c4da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1c39a9da57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1c39ab3ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x0000003051c1ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002b1c44fd5ef2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002b1c44fd63f5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002b1c46009cb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002b1c6002909f in __cf_44 ()
#10 0x00002b1c3a2762b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002b1c3a276e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002b1c3a25fe7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002b1c3a26d0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002b1c3a26bdf5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002b1c3a26add3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b1c3a267d1b in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002b1c39a7540e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002b1c39a7719b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002b1c39a772be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002b1c39a787c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002b1c39a9c4da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1c39a9da57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1c39ab3ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x0000003051c1ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================



 *** Break *** floating point exception



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2b1c46d4c700 (LWP 1264157)):
#0  0x0000003051ce91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b1c467753e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1c46771c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002b1c46770447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2b1c46f4d700 (LWP 1264158)):
#0  0x000000305200f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002b1c46770bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1c468b7f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002b1c468b8079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2b1c4714e700 (LWP 1264159)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2b1c4734f700 (LWP 1264160)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2b1c47550700 (LWP 1264161)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b1c39b86d80 (LWP 1264077)):
#0  0x0000003051cac86d in waitpid () from /lib64/libc.so.6
#1  0x0000003051c3e479 in do_system () from /lib64/libc.so.6
#2  0x0000003051c3e7b0 in system () from /lib64/libc.so.6
#3  0x00002b1c3ac1fc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002b1c3ac21bfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002b1c44fd5ef2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002b1c44fd63f5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002b1c46009cb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002b1c6002909f in __cf_44 ()
#10 0x00002b1c3a2762b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002b1c3a276e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002b1c3a25fe7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002b1c3a26d0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002b1c3a26bdf5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002b1c3a26add3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b1c3a267877 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002b1c39a7540e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002b1c39a7719b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002b1c39a772be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002b1c39a787c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002b1c39a9c4da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1c39a9da57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1c39ab3ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x0000003051c1ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002b1c44fd5ef2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002b1c44fd63f5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002b1c46009cb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002b1c6002909f in __cf_44 ()
#10 0x00002b1c3a2762b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002b1c3a276e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002b1c3a25fe7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002b1c3a26d0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002b1c3a26bdf5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002b1c3a26add3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b1c3a267877 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002b1c39a7540e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002b1c39a7719b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002b1c39a772be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002b1c39a787c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002b1c39a9c4da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1c39a9da57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1c39ab3ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x0000003051c1ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================


Traceback (most recent call last):
  File "./runSystematics.py", line 577, in <module>
    main()
  File "./runSystematics.py", line 274, in main
    process.run()
  File "/storage/local/data1/condor/execute/dir_1261924/HiggsAnalysis/.python/HiggsAnalysis/NtupleAnalysis/main.py", line 651, in run
    tchain.Process(tselector)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  Long64_t TChain::Process(const char* filename, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    could not convert argument 1 (expected string or Unicode object, SelectorImpl found)
  Long64_t TChain::Process(TSelector* selector, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    problem in C++; program state has been reset

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2b1c46d4c700 (LWP 1264157)):
#0  0x0000003051ce91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b1c467753e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1c46771c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002b1c46770447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2b1c46f4d700 (LWP 1264158)):
#0  0x000000305200f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002b1c46770bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1c468b7f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002b1c468b8079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2b1c4714e700 (LWP 1264159)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2b1c4734f700 (LWP 1264160)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2b1c47550700 (LWP 1264161)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b1c39b86d80 (LWP 1264077)):
#0  0x0000003051cac86d in waitpid () from /lib64/libc.so.6
#1  0x0000003051c3e479 in do_system () from /lib64/libc.so.6
#2  0x0000003051c3e7b0 in system () from /lib64/libc.so.6
#3  0x00002b1c3ac1fc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002b1c3ac21bfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002b1c3ab44f60 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002b1c3aa9fef2 in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#8  0x00002b1c3aaa04c9 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#9  0x00002b1c60162027 in __cf_356 ()
#10 0x00002b1c3a2762b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002b1c3a25fa3f in PyROOT::TVoidExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002b1c3a26d0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002b1c3a26bdf5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002b1c3a26add3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002b1c3a267fe1 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#17 0x00002b1c39a7540e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#18 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#19 0x00002b1c399f2985 in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#20 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#21 0x00002b1c39a72aa3 in PyEval_EvalFrameEx () at Python/ceval.c:4334
#22 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002b1c399f28bc in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#24 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1c39a712e7 in PyEval_CallObjectWithKeywords () at Python/ceval.c:3890
#26 0x00002b1c39a9d257 in Py_Finalize () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x00002b1c39ab343f in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#28 0x0000003051c1ed1d in __libc_start_main () from /lib64/libc.so.6
#29 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002b1c3ab44f60 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002b1c3aa9fef2 in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#8  0x00002b1c3aaa04c9 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#9  0x00002b1c60162027 in __cf_356 ()
#10 0x00002b1c3a2762b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002b1c3a25fa3f in PyROOT::TVoidExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002b1c3a26d0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002b1c3a26bdf5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002b1c3a26add3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002b1c3a267fe1 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#17 0x00002b1c39a7540e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#18 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#19 0x00002b1c399f2985 in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#20 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#21 0x00002b1c39a72aa3 in PyEval_EvalFrameEx () at Python/ceval.c:4334
#22 0x00002b1c39a786a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002b1c399f28bc in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#24 0x00002b1c399c1133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1c39a712e7 in PyEval_CallObjectWithKeywords () at Python/ceval.c:3890
#26 0x00002b1c39a9d257 in Py_Finalize () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x00002b1c39ab343f in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#28 0x0000003051c1ed1d in __libc_start_main () from /lib64/libc.so.6
#29 0x00000000004006b1 in _start ()
===========================================================


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/ROOT.py", line 623, in cleanup
    gROOT.EndOfProcessCleanups()
SystemError: void TROOT::EndOfProcessCleanups() =>
    problem in C++; program state has been reset
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/ROOT.py", line 623, in cleanup
    gROOT.EndOfProcessCleanups()
SystemError: void TROOT::EndOfProcessCleanups() =>
    problem in C++; program state has been reset

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2b1c46d4c700 (LWP 1264157)):
#0  0x0000003051ce91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b1c467753e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1c46771c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002b1c46770447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2b1c46f4d700 (LWP 1264158)):
#0  0x000000305200f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002b1c46770bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1c468b7f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002b1c468b8079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2b1c4714e700 (LWP 1264159)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2b1c4734f700 (LWP 1264160)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2b1c47550700 (LWP 1264161)):
#0  0x0000003051ce5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1c46910c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1c46910df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x0000003052007aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003051ce8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b1c39b86d80 (LWP 1264077)):
#0  0x0000003051cac86d in waitpid () from /lib64/libc.so.6
#1  0x0000003051c3e479 in do_system () from /lib64/libc.so.6
#2  0x0000003051c3e7b0 in system () from /lib64/libc.so.6
#3  0x00002b1c3ac1fc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002b1c3ac21bfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002b1c3ab44f60 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002b1c3aa9fef2 in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#8  0x0000003051c35992 in exit () from /lib64/libc.so.6
#9  0x0000003051c1ed24 in __libc_start_main () from /lib64/libc.so.6
#10 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002b1c3ab44f60 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002b1c3aa9fef2 in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#8  0x0000003051c35992 in exit () from /lib64/libc.so.6
#9  0x0000003051c1ed24 in __libc_start_main () from /lib64/libc.so.6
#10 0x00000000004006b1 in _start ()
===========================================================


Segmentation fault
echodrwxr-xr-x: Command not found.
[2MB/5.379MB][ 37%][==================>                               ][2MB/s]  [5.379MB/5.379MB][100%][==================================================][5.379MB/s]  [5.379MB/5.379MB][100%][==================================================][5.379MB/s]  
