Error in <TCling::RegisterModule>: cannot find dictionary module FrameworkDict_rdict.pcm

 *** Break *** floating point exception



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2ad3bc7fd700 (LWP 2504999)):
#0  0x000000338b8e91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002ad3bc2263e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002ad3bc222c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002ad3bc221447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2ad3bc9fe700 (LWP 2505000)):
#0  0x000000338bc0f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002ad3bc221bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002ad3bc368f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002ad3bc369079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2ad3bcbff700 (LWP 2505001)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2ad3bce00700 (LWP 2505002)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2ad3bd001700 (LWP 2505003)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2ad3af674d80 (LWP 2504342)):
#0  0x000000338b8ac86d in waitpid () from /lib64/libc.so.6
#1  0x000000338b83e479 in do_system () from /lib64/libc.so.6
#2  0x000000338b83e7b0 in system () from /lib64/libc.so.6
#3  0x00002ad3b06ecc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002ad3b06eebfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002ad3baaa27e2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002ad3baaa2ce5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002ad3bbabacb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002ad3d802909f in __cf_44 ()
#10 0x00002ad3afd432b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002ad3afd43e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002ad3afd2ce7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002ad3afd3a0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002ad3afd38df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002ad3afd37dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002ad3afd34d1b in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002ad3af56340e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002ad3af56519b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002ad3af5652be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002ad3af5667c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002ad3af58a4da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002ad3af58ba57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002ad3af5a1ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x000000338b81ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002ad3baaa27e2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002ad3baaa2ce5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002ad3bbabacb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002ad3d802909f in __cf_44 ()
#10 0x00002ad3afd432b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002ad3afd43e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002ad3afd2ce7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002ad3afd3a0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002ad3afd38df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002ad3afd37dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002ad3afd34d1b in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002ad3af56340e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002ad3af56519b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002ad3af5652be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002ad3af5667c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002ad3af58a4da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002ad3af58ba57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002ad3af5a1ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x000000338b81ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================



 *** Break *** floating point exception



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2ad3bc7fd700 (LWP 2504999)):
#0  0x000000338b8e91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002ad3bc2263e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002ad3bc222c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002ad3bc221447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2ad3bc9fe700 (LWP 2505000)):
#0  0x000000338bc0f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002ad3bc221bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002ad3bc368f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002ad3bc369079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2ad3bcbff700 (LWP 2505001)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2ad3bce00700 (LWP 2505002)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2ad3bd001700 (LWP 2505003)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2ad3af674d80 (LWP 2504342)):
#0  0x000000338b8ac86d in waitpid () from /lib64/libc.so.6
#1  0x000000338b83e479 in do_system () from /lib64/libc.so.6
#2  0x000000338b83e7b0 in system () from /lib64/libc.so.6
#3  0x00002ad3b06ecc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002ad3b06eebfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002ad3baaa27e2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002ad3baaa2ce5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002ad3bbabacb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002ad3d802909f in __cf_44 ()
#10 0x00002ad3afd432b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002ad3afd43e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002ad3afd2ce7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002ad3afd3a0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002ad3afd38df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002ad3afd37dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002ad3afd34877 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002ad3af56340e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002ad3af56519b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002ad3af5652be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002ad3af5667c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002ad3af58a4da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002ad3af58ba57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002ad3af5a1ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x000000338b81ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002ad3baaa27e2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002ad3baaa2ce5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002ad3bbabacb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002ad3d802909f in __cf_44 ()
#10 0x00002ad3afd432b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002ad3afd43e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002ad3afd2ce7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002ad3afd3a0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002ad3afd38df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002ad3afd37dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002ad3afd34877 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002ad3af56340e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002ad3af56519b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002ad3af5652be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002ad3af5667c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002ad3af58a4da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002ad3af58ba57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002ad3af5a1ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x000000338b81ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================


Traceback (most recent call last):
  File "./runSystematics.py", line 501, in <module>
    main()
  File "./runSystematics.py", line 238, in main
    process.run()
  File "/storage/local/data1/condor/execute/dir_2454256/HiggsAnalysis/.python/HiggsAnalysis/NtupleAnalysis/main.py", line 651, in run
    tchain.Process(tselector)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  Long64_t TChain::Process(const char* filename, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    could not convert argument 1 (expected string or Unicode object, SelectorImpl found)
  Long64_t TChain::Process(TSelector* selector, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    problem in C++; program state has been reset

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2ad3bc7fd700 (LWP 2504999)):
#0  0x000000338b8e91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002ad3bc2263e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002ad3bc222c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002ad3bc221447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2ad3bc9fe700 (LWP 2505000)):
#0  0x000000338bc0f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002ad3bc221bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002ad3bc368f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002ad3bc369079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2ad3bcbff700 (LWP 2505001)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2ad3bce00700 (LWP 2505002)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2ad3bd001700 (LWP 2505003)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2ad3af674d80 (LWP 2504342)):
#0  0x000000338b8ac86d in waitpid () from /lib64/libc.so.6
#1  0x000000338b83e479 in do_system () from /lib64/libc.so.6
#2  0x000000338b83e7b0 in system () from /lib64/libc.so.6
#3  0x00002ad3b06ecc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002ad3b06eebfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002ad3b0611f60 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002ad3b056cef2 in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#8  0x00002ad3b056d4c9 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#9  0x00002ad3d825c027 in __cf_606 ()
#10 0x00002ad3afd432b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002ad3afd2ca3f in PyROOT::TVoidExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002ad3afd3a0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002ad3afd38df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002ad3afd37dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002ad3afd34fe1 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#17 0x00002ad3af56340e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#18 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#19 0x00002ad3af4e0985 in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#20 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#21 0x00002ad3af560aa3 in PyEval_EvalFrameEx () at Python/ceval.c:4334
#22 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002ad3af4e08bc in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#24 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002ad3af55f2e7 in PyEval_CallObjectWithKeywords () at Python/ceval.c:3890
#26 0x00002ad3af58b257 in Py_Finalize () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x00002ad3af5a143f in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#28 0x000000338b81ed1d in __libc_start_main () from /lib64/libc.so.6
#29 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002ad3b0611f60 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002ad3b056cef2 in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#8  0x00002ad3b056d4c9 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#9  0x00002ad3d825c027 in __cf_606 ()
#10 0x00002ad3afd432b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002ad3afd2ca3f in PyROOT::TVoidExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002ad3afd3a0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002ad3afd38df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002ad3afd37dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002ad3afd34fe1 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#17 0x00002ad3af56340e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#18 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#19 0x00002ad3af4e0985 in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#20 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#21 0x00002ad3af560aa3 in PyEval_EvalFrameEx () at Python/ceval.c:4334
#22 0x00002ad3af5666a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002ad3af4e08bc in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#24 0x00002ad3af4af133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002ad3af55f2e7 in PyEval_CallObjectWithKeywords () at Python/ceval.c:3890
#26 0x00002ad3af58b257 in Py_Finalize () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x00002ad3af5a143f in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#28 0x000000338b81ed1d in __libc_start_main () from /lib64/libc.so.6
#29 0x00000000004006b1 in _start ()
===========================================================


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/ROOT.py", line 623, in cleanup
    gROOT.EndOfProcessCleanups()
SystemError: void TROOT::EndOfProcessCleanups() =>
    problem in C++; program state has been reset
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/ROOT.py", line 623, in cleanup
    gROOT.EndOfProcessCleanups()
SystemError: void TROOT::EndOfProcessCleanups() =>
    problem in C++; program state has been reset

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2ad3bc7fd700 (LWP 2504999)):
#0  0x000000338b8e91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002ad3bc2263e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002ad3bc222c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002ad3bc221447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2ad3bc9fe700 (LWP 2505000)):
#0  0x000000338bc0f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002ad3bc221bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002ad3bc368f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002ad3bc369079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2ad3bcbff700 (LWP 2505001)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2ad3bce00700 (LWP 2505002)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2ad3bd001700 (LWP 2505003)):
#0  0x000000338b8e5419 in syscall () from /lib64/libc.so.6
#1  0x00002ad3bc3c1c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002ad3bc3c1df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x000000338bc07aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x000000338b8e8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2ad3af674d80 (LWP 2504342)):
#0  0x000000338b8ac86d in waitpid () from /lib64/libc.so.6
#1  0x000000338b83e479 in do_system () from /lib64/libc.so.6
#2  0x000000338b83e7b0 in system () from /lib64/libc.so.6
#3  0x00002ad3b06ecc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002ad3b06eebfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002ad3b0611f60 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002ad3b056cef2 in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#8  0x000000338b835992 in exit () from /lib64/libc.so.6
#9  0x000000338b81ed24 in __libc_start_main () from /lib64/libc.so.6
#10 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002ad3b0611f60 in TDirectory::CleanTargets() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002ad3b056cef2 in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#8  0x000000338b835992 in exit () from /lib64/libc.so.6
#9  0x000000338b81ed24 in __libc_start_main () from /lib64/libc.so.6
#10 0x00000000004006b1 in _start ()
===========================================================


Segmentation fault
echodrwxr-xr-x: Command not found.
[2MB/33.9MB][  5%][==>                                               ][0B/s]  [33.9MB/33.9MB][100%][==================================================][0B/s]  [33.9MB/33.9MB][100%][==================================================][0B/s]  
