Error in <TCling::RegisterModule>: cannot find dictionary module FrameworkDict_rdict.pcm

 *** Break *** floating point exception



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2b159517e700 (LWP 2990608)):
#0  0x00000038a4ee91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b1594ba73e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1594ba3c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002b1594ba2447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2b159537f700 (LWP 2990609)):
#0  0x00000038a520f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002b1594ba2bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1594ce9f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002b1594cea079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2b1595580700 (LWP 2990610)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2b1595781700 (LWP 2990611)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2b1595982700 (LWP 2990612)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b1587fbcd80 (LWP 2989656)):
#0  0x00000038a4eac86d in waitpid () from /lib64/libc.so.6
#1  0x00000038a4e3e479 in do_system () from /lib64/libc.so.6
#2  0x00000038a4e3e7b0 in system () from /lib64/libc.so.6
#3  0x00002b158906dc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002b158906fbfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002b15934237e2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_2947086/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002b1593423ce5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_2947086/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002b159443bcb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002b15b002909f in __cf_44 ()
#10 0x00002b15886c42b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002b15886c4e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002b15886ade7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002b15886bb0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002b15886b9df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002b15886b8dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b15886b5877 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b1587df7133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002b1587eab40e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002b1587eae6a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002b1587ead19b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002b1587ead2be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002b1587eae6a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002b1587eae7c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002b1587ed24da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1587ed3a57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1587ee9ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x00000038a4e1ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002b15934237e2 in SelectorImpl::printStatus() () from /storage/local/data1/condor/execute/dir_2947086/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#7  0x00002b1593423ce5 in SelectorImpl::Process(long long) () from /storage/local/data1/condor/execute/dir_2947086/HiggsAnalysis/NtupleAnalysis/lib/libHPlusAnalysis.so
#8  0x00002b159443bcb8 in TTreePlayer::Process(TSelector*, char const*, long long, long long) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTreePlayer.so
#9  0x00002b15b002909f in __cf_44 ()
#10 0x00002b15886c42b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#11 0x00002b15886c4e90 in Cppyy::CallLL(long, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#12 0x00002b15886ade7f in PyROOT::TLongLongExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#13 0x00002b15886bb0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#14 0x00002b15886b9df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#15 0x00002b15886b8dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b15886b5877 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b1587df7133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#18 0x00002b1587eab40e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#19 0x00002b1587eae6a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#20 0x00002b1587ead19b in PyEval_EvalFrameEx () at Python/ceval.c:4117
#21 0x00002b1587ead2be in PyEval_EvalFrameEx () at Python/ceval.c:4107
#22 0x00002b1587eae6a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#23 0x00002b1587eae7c9 in PyEval_EvalCode () at Python/ceval.c:667
#24 0x00002b1587ed24da in PyRun_FileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1587ed3a57 in PyRun_SimpleFileExFlags () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1587ee9ab5 in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x00000038a4e1ed1d in __libc_start_main () from /lib64/libc.so.6
#28 0x00000000004006b1 in _start ()
===========================================================


Traceback (most recent call last):
  File "./runSystematics.py", line 543, in <module>
    main()
  File "./runSystematics.py", line 259, in main
    process.run()
  File "/storage/local/data1/condor/execute/dir_2947086/HiggsAnalysis/.python/HiggsAnalysis/NtupleAnalysis/main.py", line 651, in run
    tchain.Process(tselector)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  Long64_t TChain::Process(const char* filename, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    could not convert argument 1 (expected string or Unicode object, SelectorImpl found)
  Long64_t TChain::Process(TSelector* selector, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    problem in C++; program state has been reset

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2b159517e700 (LWP 2990608)):
#0  0x00000038a4ee91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b1594ba73e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1594ba3c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002b1594ba2447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2b159537f700 (LWP 2990609)):
#0  0x00000038a520f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002b1594ba2bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1594ce9f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002b1594cea079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2b1595580700 (LWP 2990610)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2b1595781700 (LWP 2990611)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2b1595982700 (LWP 2990612)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b1587fbcd80 (LWP 2989656)):
#0  0x00000038a4eac86d in waitpid () from /lib64/libc.so.6
#1  0x00000038a4e3e479 in do_system () from /lib64/libc.so.6
#2  0x00000038a4e3e7b0 in system () from /lib64/libc.so.6
#3  0x00002b158906dc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002b158906fbfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002b1588f93753 in TDirectory::RegisterContext(TDirectory::TContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002b1588cc4b1b in TDirectoryFile::Save() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#8  0x00002b1588cc2ebc in TDirectoryFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#9  0x00002b1588d109e4 in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#10 0x00002b1594b73c77 in TNetXNGFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libNetxNG.so
#11 0x00002b1588eed3a0 in (anonymous namespace)::R__ListSlowClose(TList*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#12 0x00002b1588eedede in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#13 0x00002b1588eee4c9 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#14 0x00002b15b0110027 in __cf_274 ()
#15 0x00002b15886c42b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b15886ada3f in PyROOT::TVoidExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b15886bb0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#18 0x00002b15886b9df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#19 0x00002b15886b8dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#20 0x00002b15886b5fe1 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#21 0x00002b1587df7133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#22 0x00002b1587eab40e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#23 0x00002b1587eae6a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#24 0x00002b1587e28985 in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1587df7133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1587ea8aa3 in PyEval_EvalFrameEx () at Python/ceval.c:4334
#27 0x00002b1587eae6a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#28 0x00002b1587e288bc in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#29 0x00002b1587df7133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#30 0x00002b1587ea72e7 in PyEval_CallObjectWithKeywords () at Python/ceval.c:3890
#31 0x00002b1587ed3257 in Py_Finalize () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#32 0x00002b1587ee943f in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#33 0x00000038a4e1ed1d in __libc_start_main () from /lib64/libc.so.6
#34 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002b1588f93753 in TDirectory::RegisterContext(TDirectory::TContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002b1588cc4b1b in TDirectoryFile::Save() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#8  0x00002b1588cc2ebc in TDirectoryFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#9  0x00002b1588d109e4 in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#10 0x00002b1594b73c77 in TNetXNGFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libNetxNG.so
#11 0x00002b1588eed3a0 in (anonymous namespace)::R__ListSlowClose(TList*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#12 0x00002b1588eedede in TROOT::CloseFiles() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#13 0x00002b1588eee4c9 in TROOT::EndOfProcessCleanups() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#14 0x00002b15b0110027 in __cf_274 ()
#15 0x00002b15886c42b1 in FastCall(long, void*, void*, void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#16 0x00002b15886ada3f in PyROOT::TVoidExecutor::Execute(long, void*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b15886bb0bd in PyROOT::TMethodHolder::CallSafe(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#18 0x00002b15886b9df5 in PyROOT::TMethodHolder::Execute(void*, long, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#19 0x00002b15886b8dd3 in PyROOT::TMethodHolder::Call(PyROOT::ObjectProxy*&, _object*, _object*, PyROOT::TCallContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#20 0x00002b15886b5fe1 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#21 0x00002b1587df7133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#22 0x00002b1587eab40e in PyEval_EvalFrameEx () at Python/ceval.c:4239
#23 0x00002b1587eae6a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#24 0x00002b1587e28985 in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1587df7133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1587ea8aa3 in PyEval_EvalFrameEx () at Python/ceval.c:4334
#27 0x00002b1587eae6a0 in PyEval_EvalCodeEx () at Python/ceval.c:3253
#28 0x00002b1587e288bc in function_call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#29 0x00002b1587df7133 in PyObject_Call () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#30 0x00002b1587ea72e7 in PyEval_CallObjectWithKeywords () at Python/ceval.c:3890
#31 0x00002b1587ed3257 in Py_Finalize () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#32 0x00002b1587ee943f in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#33 0x00000038a4e1ed1d in __libc_start_main () from /lib64/libc.so.6
#34 0x00000000004006b1 in _start ()
===========================================================


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/ROOT.py", line 623, in cleanup
    gROOT.EndOfProcessCleanups()
SystemError: void TROOT::EndOfProcessCleanups() =>
    problem in C++; program state has been reset
Error in sys.exitfunc:

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 6 (Thread 0x2b159517e700 (LWP 2990608)):
#0  0x00000038a4ee91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00002b1594ba73e2 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1594ba3c2d in XrdSys::IOEvents::BootStrap::Start(void*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#3  0x00002b1594ba2447 in XrdSysThread_Xeq () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#4  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x2b159537f700 (LWP 2990609)):
#0  0x00000038a520f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00002b1594ba2bdb in XrdSysTimer::Wait(int) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdUtils.so.2
#2  0x00002b1594ce9f11 in XrdCl::TaskManager::RunTasks() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00002b1594cea079 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#4  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x2b1595580700 (LWP 2990610)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x2b1595781700 (LWP 2990611)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x2b1595982700 (LWP 2990612)):
#0  0x00000038a4ee5419 in syscall () from /lib64/libc.so.6
#1  0x00002b1594d42c63 in XrdCl::JobManager::RunJobs() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#2  0x00002b1594d42df9 in ?? () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/xrootd/4.0.4-kpegke2/lib/libXrdCl.so.2
#3  0x00000038a5207aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000038a4ee8bcd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x2b1587fbcd80 (LWP 2989656)):
#0  0x00000038a4eac86d in waitpid () from /lib64/libc.so.6
#1  0x00000038a4e3e479 in do_system () from /lib64/libc.so.6
#2  0x00000038a4e3e7b0 in system () from /lib64/libc.so.6
#3  0x00002b158906dc2a in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#4  0x00002b158906fbfc in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#5  <signal handler called>
#6  0x00002b1588f93753 in TDirectory::RegisterContext(TDirectory::TContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002b1588cc4b1b in TDirectoryFile::Save() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#8  0x00002b1588cc2ebc in TDirectoryFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#9  0x00002b1588d109e4 in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#10 0x00002b1594b73c77 in TNetXNGFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libNetxNG.so
#11 0x00002b1594b73f0f in TNetXNGFile::~TNetXNGFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libNetxNG.so
#12 0x00002b1594b74119 in TNetXNGFile::~TNetXNGFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libNetxNG.so
#13 0x00002b15887bed71 in TChain::~TChain() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTree.so
#14 0x00002b15887beea9 in TChain::~TChain() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTree.so
#15 0x00002b1589044903 in TClass::Destructor(void*, bool) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#16 0x00002b15886aa6cf in PyROOT::op_dealloc_nofree(PyROOT::ObjectProxy*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b15886aa819 in PyROOT::(anonymous namespace)::op_dealloc(PyROOT::ObjectProxy*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#18 0x00002b1587e5c072 in subtype_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#19 0x00002b1587e27679 in frame_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#20 0x00002b1587edb97b in tb_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#21 0x00002b1587edb98b in tb_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#22 0x00002b1587edb98b in tb_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#23 0x00002b1587e3cc17 in insertdict () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#24 0x00002b1587e3e157 in PyDict_SetItem () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1587e3f7a8 in PyDict_SetItemString () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1587ed2fae in PyErr_PrintEx () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x00002b1587ed33ae in Py_Finalize () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#28 0x00002b1587ee943f in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#29 0x00000038a4e1ed1d in __libc_start_main () from /lib64/libc.so.6
#30 0x00000000004006b1 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002b1588f93753 in TDirectory::RegisterContext(TDirectory::TContext*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#7  0x00002b1588cc4b1b in TDirectoryFile::Save() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#8  0x00002b1588cc2ebc in TDirectoryFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#9  0x00002b1588d109e4 in TFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libRIO.so
#10 0x00002b1594b73c77 in TNetXNGFile::Close(char const*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libNetxNG.so
#11 0x00002b1594b73f0f in TNetXNGFile::~TNetXNGFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libNetxNG.so
#12 0x00002b1594b74119 in TNetXNGFile::~TNetXNGFile() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libNetxNG.so
#13 0x00002b15887bed71 in TChain::~TChain() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTree.so
#14 0x00002b15887beea9 in TChain::~TChain() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libTree.so
#15 0x00002b1589044903 in TClass::Destructor(void*, bool) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libCore.so
#16 0x00002b15886aa6cf in PyROOT::op_dealloc_nofree(PyROOT::ObjectProxy*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#17 0x00002b15886aa819 in PyROOT::(anonymous namespace)::op_dealloc(PyROOT::ObjectProxy*) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/lcg/root/6.06.00/lib/libPyROOT.so
#18 0x00002b1587e5c072 in subtype_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#19 0x00002b1587e27679 in frame_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#20 0x00002b1587edb97b in tb_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#21 0x00002b1587edb98b in tb_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#22 0x00002b1587edb98b in tb_dealloc () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#23 0x00002b1587e3cc17 in insertdict () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#24 0x00002b1587e3e157 in PyDict_SetItem () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#25 0x00002b1587e3f7a8 in PyDict_SetItemString () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#26 0x00002b1587ed2fae in PyErr_PrintEx () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#27 0x00002b1587ed33ae in Py_Finalize () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#28 0x00002b1587ee943f in Py_Main () from /cvmfs/cms.cern.ch/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/libpython2.7.so.1.0
#29 0x00000038a4e1ed1d in __libc_start_main () from /lib64/libc.so.6
#30 0x00000000004006b1 in _start ()
===========================================================


Segmentation fault
echodrwxr-xr-x: Command not found.
[3.329kB/3.329kB][100%][==================================================][3.329kB/s]  [3.329kB/3.329kB][100%][==================================================][3.329kB/s]  
